[package]
name = "aoc-2024"
version = "0.1.0"
edition = "2021"

[dependencies]
polars = { version = "0.45.1", features = [
    "lazy",
    "abs",
    "is_in",
    "dtype-struct",
    "list_sets",
] }
